server:
  port: 8282
  servlet:
    context-path: /token
  error:
    include-message: always

service:
  client-token:
    name: keycloak
    grant-type: client_credentials
    url: http://localhost:8080/realms/tokenManagement/protocol/openid-connect/token
    client-id: clientIdTest
    client-secret: clientSecretTest